# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e543de20edd8e246dc390bfaeff6faf9d59d917b5706e3efa8633df6baf8d9db844339b1d7efb6be525380d06f39ca732bf0cfe91577c470a4614dcfd66efab

test:
  secret_key_base: 07eb1f0525fc5386905ddb01cd4fed3f4e64c026b085d38eeafc17b4d1610e71ecbefce66899ffecfbdb1f4e7aa125c7b349650cb2b514e75eafb002abc3a234

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
